### ISSUE TITLE
"iTunes Transporter successfully finished its job" but pilot ends with an error

### ISSUE THREAD

**Issue by lifeisfoo** [fastlane/pilot#110]
I've an issue very similar to fastlane/deliver#124 and fastlane/deliver#44 but with pilot 1.2.0.
I'm using it with fastlane, calling it without parameters.
```
  lane :beta do
    gym
    pilot
  end

```

After the ipa file was transferred, an operation called `uploadDoneWithArguments` was executed ending with a timeout, then was executed a second time ending correctly (`Apple's web service operation return value: parameter Success = true`), but seems that pilot is not handling correctly this. At the end of the output it first prints "`iTunes Transporter successfully finished its job`", and then "`Error uploading ipa file, more information see above`", ending with an error.

Complete logs:
```
[09:41:16]: [Transporter]: DBG-X: The status for the file, b5b4f7feb96abd046e9b54511dcf9984.ipa, is TRANSFERRED.
[09:41:16]: [Transporter]: INFO: Package upload progress: 100% completed
[09:41:18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[09:41:18]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[09:41:18]: [Transporter]: INFO: The file, metadata.xml, was uploaded successfully.
[09:41:18]: [Transporter]: INFO: The file, b5b4f7feb96abd046e9b54511dcf9984.ipa, was uploaded successfully.
[09:41:18]: [Transporter]: INFO: The status for the upload is SUCCESSFUL.
[09:41:18]: [Transporter]: INFO: The package's files (1066879813.itmsp) uploaded successfully.
[09:41:18]: [Transporter]: INFO: Done performing upload.
[09:41:18]: [Transporter]: DBG-X: The transfer time for the package 1066879813.itmsp was 1000734 milliseconds.
[09:41:18]: [Transporter]: DBG-X: Throughput information for 1066879813.itmsp: 16 minutes, 40,73 seconds, 42,00MB, 42,97KB/sec
[09:41:18]: [Transporter]: INFO: Performing uploadDone notification to Apple for package 1066879813.itmsp ...
[09:41:18]: [Transporter]: DBG-X: Deflated 814 bytes to 404
[09:41:18]: [Transporter]: DBG-X: Memory: [JVM] 936M free, 980M total, 980M max [System] (Physical) 365M free, 10240M total (Swap) 615M free, 1024M total
[09:41:18]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
[09:41:18]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:41:18]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:41:18]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[09:41:18]: [Transporter]: DBG-X:   parameter CPUToken = 1a7d8997-bec1-49f7-a9dc-fff7c35b34c7/1450340674995
[09:41:18]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=44038402, CalculatedChecksum=8c1de3251f3af41363bfc9d5cf7d26f3, FileLastModified=1450340581000, Filename=b5b4f7feb96abd046e9b54511dcf9984.ipa, CalculationTime=201}]
[09:41:18]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
[09:41:18]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=433, b5b4f7feb96abd046e9b54511dcf9984.ipa=44038402}
[09:41:18]: [Transporter]: DBG-X:   parameter NewPackageName = 1066879813-20151217002435-284.itmsp
[09:41:18]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 44038835
[09:41:18]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[09:41:18]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/MyCompany
[09:41:18]: [Transporter]: DBG-X:   parameter Throttle = 100000
[09:41:18]: [Transporter]: DBG-X:   parameter TransferTime = 1000734
[09:41:18]: [Transporter]: DBG-X:   parameter Transport = Signiant
[09:41:18]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
[09:41:18]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u my@email.me -p **hidden value** -f /tmp/1066879813.itmsp -t Signiant -k 100000
[09:41:18]: [Transporter]: DBG-X:   parameter Username = my@email.me
[09:41:18]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[09:41:18]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[09:41:18]: [Transporter]: INFO: id = 20151217094118-688
[09:51:34]: [Transporter Error Output]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
[09:51:34]: [Transporter Error Output]: An exception has occurred: Operation timed out
[09:51:34]: [Transporter]: DEBUG: java.net.SocketException: Operation timed out
[09:52:04]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
[09:52:04]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[09:52:04]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[09:52:04]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[09:52:04]: [Transporter]: DBG-X:   parameter CPUToken = 1a7d8997-bec1-49f7-a9dc-fff7c35b34c7/1450340674995
[09:52:04]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=44038402, CalculatedChecksum=8c1de3251f3af41363bfc9d5cf7d26f3, FileLastModified=1450340581000, Filename=b5b4f7feb96abd046e9b54511dcf9984.ipa, CalculationTime=201}]
[09:52:04]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
[09:52:04]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=433, b5b4f7feb96abd046e9b54511dcf9984.ipa=44038402}
[09:52:04]: [Transporter]: DBG-X:   parameter NewPackageName = 1066879813-20151217002435-284.itmsp
[09:52:04]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 44038835
[09:52:04]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.1 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[09:52:04]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/MyCompany
[09:52:04]: [Transporter]: DBG-X:   parameter Throttle = 100000
[09:52:04]: [Transporter]: DBG-X:   parameter TransferTime = 1000734
[09:52:04]: [Transporter]: DBG-X:   parameter Transport = Signiant
[09:52:04]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
[09:52:04]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u my@email.me -p **hidden value** -f /tmp/1066879813.itmsp -t Signiant -k 100000
[09:52:04]: [Transporter]: DBG-X:   parameter Username = my@email.me
[09:52:04]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[09:52:04]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[09:52:04]: [Transporter]: INFO: id = 20151217095204-080
[09:52:07]: [Transporter]: DBG-X: Apple's web service operation return value:
[09:52:07]: [Transporter]: DBG-X:   parameter Success = true
[09:52:08]: [Transporter]: DBG-X: Unlocking token at path /Users/alessandro/.itmstransporter/UploadTokens/MacBook-Pro-di-Alessandro.local_MyCompany_1066879813.itmsp.token
[09:52:08]: [Transporter]: DBG-X: Releasing token file lock
[09:52:08]: [Transporter]: DBG-X: Removing token at path /Users/alessandro/.itmstransporter/UploadTokens/MacBook-Pro-di-Alessandro.local_MyCompany_1066879813.itmsp.token
[09:52:08]: [Transporter]: INFO: Done performing uploadDone notification to Apple.
[09:52:08]: [Transporter]: INFO: The package: /tmp/1066879813.itmsp has been successfully uploaded.
[09:52:08]: iTunes Transporter successfully finished its job
[09:52:08]: [Transporter]: DBG-X: Returning 0
[09:52:08]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
An exception has occurred: Operation timed out
[09:52:08]: Variable Dump:
[09:52:08]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/alessandro/Dev/MyCompany/MyApp/MyApp.ipa", :DSYM_OUTPUT_PATH=>"/Users/alessandro/Dev/MyCompany/MyApp/MyApp.app.dSYM.zip"}
[09:52:08]: Error uploading ipa file, more information see above

```

Error stack: 
```
/Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/pilot-1.2.0/lib/pilot/build_manager.rb:27:in `upload': Error uploading ipa file, more information see above (RuntimeError)
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Users/alessandro/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
[cut]
```

**Comment by aleufms** [comment]
Same error here.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1886. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
