### ISSUE TITLE
TEAM_ID selection on environment variable not working

### ISSUE THREAD

**Issue by pabloromeu** [fastlane/pilot#143]
I am working using an iTunes User with several teams. I setup the environment variable for the team id and it does not select it automatically

     ITUNESCONNECT_TEAM_ID           = "333" 
     ENV["PILOT_TEAM_ID"]              = ITUNESCONNECT_TEAM_ID

But it does not work:

     [13:30:03]: Login to iTunes Connect (whatever@ever.es)
     Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
     1) "First" (111)
     2) "Second" (222)
     3) "Third" (333)

Pilot version is 1.3.0

**Comment by vpolouchkine** [comment]
Does it work if you pass it using --team_id?

**Comment by pabloromeu** [comment]
This works, but asks for team id:

        pilot builds -u whatever@and.ever -a the.bundle.id

This does not, and it crashes pilot:

       pilot builds -u whatever@and.ever -a the.bundle.id --team_id 333  

```
          [16:54:25]: Login to iTunes Connect (whatever@and.ever)
fatal: Not a git repository (or any of the parent directories): .git
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '49ee634ed1fc39fe0592fb3069e244ab'
The crash report has been stored locally '/tmp/sentry_49ee634ed1fc39fe0592fb3069e244ab.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] invalid request body (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:66:in `team_id='
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/tunes_client.rb:87:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/manager.rb:16:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:32:in `list'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:57:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:120:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

```

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1877. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
