### ISSUE TITLE
This train could not be activated because there is no testable build in the train. 

### ISSUE THREAD

**Issue by jonandersen** [fastlane/pilot#158]
I'm getting an error when trying to submit an app to test flight. The build successfully uploads and appears inside the `app` section of iTunes connect (I can submit it to the App Store). The app can't be released for internal testing (there is no build showing up), but it can be released for external testers. I'm not sure what the error means `there is no testable build in the train. ` but I assume it's related to the build not being available for internal testers? 

crash number: `c9f1898c98cbc1e483e630e5c7fbc0fe`

```
/Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] This train could not be activated because there is no testable build in the train. (Spaceship::TunesClient::ITunesConnectError)
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:538:in `update_build_trains!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:64:in `block (2 levels) in parsing_binding'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:156:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:162:in `<top (required)>'
	from /Users/jonandersen/.rvm/rubies/ruby-2.1.3/bin/fastlane:23:in `load'
	from /Users/jonandersen/.rvm/rubies/ruby-2.1.3/bin/fastlane:23:in `<main>'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vpolouchkine** [comment]
Can you please share your Fastfile and the call you're making to `pilot`? Thanks!

**Comment by jonandersen** [comment]
@vpolouchkine 

i'm running `fastlane beta`

```
fastlane_version "1.49.0"

default_platform :ios
platform :ios do
  before_all do
    increment_build_number
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end
  
  
  desc "Submit a new Alpha Build to Fabric"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    # sigh
    gym(scheme: "Mixcord", use_legacy_build_api: true) 
    crashlytics(api_token: '<REMOVED>', 
      build_secret: '<REMOVED>',
      groups: 'IOS'
    )
    
    slack(
      message: "New Mixcord beta submitted to fabric.",
      slack_url: '<REMOVED>'
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sigh
    gym(scheme: "Mixcord", use_legacy_build_api: true) 
    pilot
    
    slack(
      message: "New Mixcord beta submitted to Apple.",
      slack_url: '<REMOVED>'
      
    )
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    # sigh
    gym(scheme: "Mixcord", use_legacy_build_api: true) 
    deliver(force: true)
    
    slack(
      message: "New Mixcord app submitted to App store.",
      slack_url: '<REMOVED>'
    )
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1872. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
