### ISSUE TITLE
Pilot sometimes dies when waiting for testflight to finish processing the build:

### ISSUE THREAD

**Issue by vetrovosk** [fastlane/pilot#35]
I think 3 of 5 uploads finish like this for us:

```
[00:35:20][Step 1/2] INFO [2015-09-20 00:34:18.17]: Successfully uploaded the new binary to iTunes Connect
[00:35:20][Step 1/2] INFO [2015-09-20 00:34:18.17]: Waiting for iTunes Connect to process the new build
[00:35:20][Step 1/2] [00:34:23]: GET: ra/apps/972696562/trains/
[00:35:20][Step 1/2] [00:35:20]: GET: ra/apps/972696562/trains/: {"data"=>{a lot of data here}, "statusCode"=>"SUCCESS"}
[00:36:06][Step 1/2] [00:35:20]: GET: ra/apps/972696562/trains/
[00:36:06][Step 1/2] [00:36:06]: GET: ra/apps/972696562/trains/: {"data"=>{a lot of data here}, "statusCode"=>"SUCCESS"}
[00:36:21][Step 1/2] INFO [2015-09-20 00:36:07.29]: Waiting for iTunes Connect to process the new build
[00:36:21][Step 1/2] [00:36:12]: GET: ra/apps/972696562/trains/
[00:36:21][Step 1/2] [00:36:21]: GET: ra/apps/972696562/trains/: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Could not generate a response."]}, "statusCode"=>"ERROR"}
[00:36:21][Step 1/2] /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:240:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Could not generate a response."]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/tunes/tunes_client.rb:222:in `build_trains'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/tunes/application.rb:168:in `pre_processing_builds'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/tunes/application.rb:183:in `all_processing_builds'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/build_manager.rb:68:in `block in wait_for_processing_build'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/build_manager.rb:65:in `loop'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/build_manager.rb:65:in `wait_for_processing_build'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/build_manager.rb:19:in `upload'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:48:in `block (2 levels) in run'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:120:in `run'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/lib/pilot/commands_generator.rb:17:in `start'
[00:36:21][Step 1/2] 	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.2.0/bin/pilot:6:in `<top (required)>'
[00:36:21][Step 1/2] 	from /usr/bin/pilot:23:in `load'
[00:36:21][Step 1/2] 	from /usr/bin/pilot:23:in `<main>'
[00:36:21][Step 1/2] Process exited with code 1
[00:36:22][Step 1/2] Step deploy to beta testers (Command Line) failed
```

It looks like this error is caused by some temporary itunes connect issue, so is it possible to retry number of times (possibly specified as a command line argument) instead of dying in case of such error?

I've just sent full logs to github@krausefx.com.

**Comment by KrauseFx** [comment]
`spaceship` will automatically re-send the request if there is a timeout up to 5 times. I'll take a closer look at this issue :+1:

**Comment by vetrovosk** [comment]
this is another stacktrace we sometimes see

```
[14:56:51]: Waiting for iTunes Connect to process the new build
[14:57:21]: Waiting for iTunes Connect to process the new build
[14:57:49]: Waiting for iTunes Connect to process the new build
[14:58:18]: Waiting for iTunes Connect to process the new build
[14:58:46]: Waiting for iTunes Connect to process the new build
[14:59:15]: Waiting for iTunes Connect to process the new build
[14:59:43]: Waiting for iTunes Connect to process the new build
[15:00:12]: Waiting for iTunes Connect to process the new build
[15:00:41]: Waiting for iTunes Connect to process the new build
[15:01:10]: Waiting for iTunes Connect to process the new build
[15:01:38]: Waiting for iTunes Connect to process the new build
[15:02:11]: Waiting for iTunes Connect to process the new build
[15:02:47]: Waiting for iTunes Connect to process the new build
[15:03:16]: Waiting for iTunes Connect to process the new build
[15:03:45]: Waiting for iTunes Connect to process the new build
[15:04:14]: Waiting for iTunes Connect to process the new build
[15:04:41]: Waiting for iTunes Connect to process the new build
[15:05:08]: Waiting for iTunes Connect to process the new build
[15:05:36]: Waiting for iTunes Connect to process the new build
[15:06:04]: Waiting for iTunes Connect to process the new build
[15:06:32]: Waiting for iTunes Connect to process the new build
[15:07:01]: Waiting for iTunes Connect to process the new build
[15:07:27]: Waiting for iTunes Connect to process the new build
[15:07:55]: Waiting for iTunes Connect to process the new build
[15:08:22]: Waiting for iTunes Connect to process the new build
[15:08:49]: Waiting for iTunes Connect to process the new build
[15:09:17]: Waiting for iTunes Connect to process the new build
[15:09:44]: Waiting for iTunes Connect to process the new build
[15:10:11]: Waiting for iTunes Connect to process the new build
[15:10:42]: Waiting for iTunes Connect to process the new build
[15:11:10]: Waiting for iTunes Connect to process the new build
[15:11:37]: Waiting for iTunes Connect to process the new build
[15:12:06]: Waiting for iTunes Connect to process the new build
[15:12:34]: Waiting for iTunes Connect to process the new build
[15:13:00]: Waiting for iTunes Connect to process the new build
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/client.rb:244:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
        from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/tunes_client.rb:440:in `build_trains'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/application.rb:202:in `pre_processing_builds'
        from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.11.1/lib/spaceship/tunes/application.rb:217:in `all_processing_builds'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/build_manager.rb:68:in `block in wait_for_processing_build'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/build_manager.rb:65:in `loop'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/build_manager.rb:65:in `wait_for_processing_build'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/build_manager.rb:19:in `upload'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/commands_generator.rb:48:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/commands_generator.rb:120:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/lib/pilot/commands_generator.rb:17:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-0.2.2/bin/pilot:6:in `<top (required)>'
        from /usr/local/bin/pilot:23:in `load'
        from /usr/local/bin/pilot:23:in `<main>'
bash-3.2$
```

**Comment by KrauseFx** [comment]
It seems like Apple is currently having timeout issues with iTunes Connect - this isn't an error of `pilot`

**Comment by vetrovosk** [comment]
Looks like pilot whats in infinite loop while there is at least one processing build (build_manager.rb#L72). For example, our application has a lot of processing builds, attached screenshot was made couple of minutes ago, and you can see that there are some builds in processing state since Septermber.

Can it be the cause?

<img width="921" alt="screen shot 2015-10-21 at 19 27 40" src="https://cloud.githubusercontent.com/assets/843213/10644679/36f81f14-782a-11e5-99ca-a58f2129063f.png">

**Comment by scatterbrain** [comment]
Facing the same issue. The upload actually works and I get an email from iTunes Connect about new version being available but pilot hangs with "Waiting for iTunes Connect to process the new build". I also have couple of old builds in Processing state in iTunes Connect.

**Comment by adcooley** [comment]
Yeah having the same issue as @vetrovosk. It does eventually send the email to testers, but doesn't seem to be sending push notifications

**Comment by adcooley** [comment]
Just to confirm, I'm assuming this is why the build never gets it's 'What's New' section set from the changelog option?

**Comment by salvabalza** [comment]
I've this issue as well. Since there are some builds in processing state since months, as @vetrovosk already pointed out, and we have some of them in all our apps, this is now blocking us to further check this (wonderful btw, many thanks!) tool.

**Comment by VitalyTimofeev** [comment]
+1. I believe this happens due checking on this line https://github.com/fastlane/pilot/blob/2c7b36068b66680283163188a7e101086bbffeac/lib/pilot/build_manager.rb#L73. It checks for count of all processing builds, not just for processing state of latest build.

**Comment by jalmaas** [comment]
I have the same problem. I had a couple of builds from earlier when iTC was a bit unstable that were stuck in "processing", but I can't see them anymore

**Comment by Sajjon** [comment]
I have the same problem with the 'pilot' action, it works great, but the command/Fastlane does not understand that the build in iTunes connect changed status from "processing" to ready. 

'Pilot' never terminates. So I have to interupt the fastlane lane, which results in my actions/scripts after the 'pilot' action never being executed.

What is the status here?

I really love the pilot action (and fastlane in general) btw! :+1:

**Comment by matb33** [comment]
I get the same stacktrace as vetrovosk, and it seems to happens more than half the time:

```
[12:45:44]: ------------------------------------------------------------------------------------------------------
[12:45:44]: Successfully uploaded package to iTunesConnect. It might take a few minutes until it's visible online.
[12:45:44]: ------------------------------------------------------------------------------------------------------
[12:45:44]: Successfully uploaded the new binary to iTunes Connect
[12:45:44]: Waiting for iTunes Connect to process the new build
[12:46:19]: Waiting for iTunes Connect to process the new build
[12:46:55]: Waiting for iTunes Connect to process the new build
[12:47:29]: Waiting for iTunes Connect to process the new build
[12:48:04]: Waiting for iTunes Connect to process the new build
[12:48:45]: Waiting for iTunes Connect to process the new build
[12:49:19]: Waiting for iTunes Connect to process the new build
[12:49:54]: Waiting for iTunes Connect to process the new build
[12:50:29]: Waiting for iTunes Connect to process the new build
[12:51:05]: Waiting for iTunes Connect to process the new build
[12:51:39]: Waiting for iTunes Connect to process the new build
[12:52:13]: Waiting for iTunes Connect to process the new build
[12:52:47]: Waiting for iTunes Connect to process the new build
[12:53:22]: Waiting for iTunes Connect to process the new build
[12:53:57]: Waiting for iTunes Connect to process the new build
[12:54:31]: Waiting for iTunes Connect to process the new build
[12:55:06]: Waiting for iTunes Connect to process the new build
[12:56:15]: Waiting for iTunes Connect to process the new build
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/client.rb:268:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/tunes/tunes_client.rb:514:in `build_trains'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/tunes/application.rb:202:in `pre_processing_builds'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/tunes/application.rb:231:in `all_processing_builds'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:73:in `block in wait_for_processing_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:70:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:70:in `wait_for_processing_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/build_manager.rb:21:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:120:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/lib/pilot/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.3.0/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

What's unclear is whether or not the testflight emails will eventually be sent anyway. Perhaps there could be a configuration parameter to allow us to customize how many retries we are willing to tolerate as part of our own build processes?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1915. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
