### ISSUE TITLE
undefined method `[]' for nil:NilClass (Pilot 1.0.0) Could not fetch the login URL from iTunes Connect, the server might be down (RuntimeError)

### ISSUE THREAD

**Issue by jonnyijapan** [fastlane/pilot#79]
I run:
mjgmbp:workspace jonny$ pilot builds --username myaccount@gmail.com

And get:

```
[19:38:25]: Login to iTunes Connect (myaccount@gmail.com)
undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:58:in `rescue in login_url': Could not fetch the login URL from iTunes Connect, the server might be down (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:50:in `login_url'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/tunes/tunes_client.rb:63:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/client.rb:157:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/client.rb:51:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.3/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/manager.rb:15:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/build_manager.rb:32:in `list'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:57:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:120:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/lib/pilot/commands_generator.rb:17:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.0/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

I don't think iTunes Connect is down. Web login works at least.

**Comment by jonnyijapan** [comment]
Ok I'm gonna close this now, I did a "gem update -p" and lots of things updated. Then I ran this command again, as well as "pilot upload", and things work now!

**Comment by KrauseFx** [comment]
:+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1899. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
