### ISSUE TITLE
iTunes Transporter succeeds eventually but  fastlane reports an error

### ISSUE THREAD

**Issue by meirtz4** [fastlane/pilot#84]
Look similar to [deliver #44](https://github.com/fastlane/deliver/issues/44)

Transporter fails uploading the first time due to a connectivity issue Transporter outputs this the first time ` [Transporter Error Output]: The file, df9449c4ffc10b21d76ccd444441e656.ipa, did not complete its upload.` then automatically retries and succeeds the second time.
But pilot abort with this message:

```
[10:11:25][Step 1/1] [10:11:49]: iTunes Transporter successfully finished its job
[10:11:25][Step 1/1] [10:11:49]: [Transporter]: DBG-X: Returning 0
[10:11:25][Step 1/1] [10:11:49]: The file, df9449c4ffc10b21d76ccd444441e656.ipa, did not complete its upload.
[10:11:25][Step 1/1] [10:11:49]: Variable Dump:
[10:11:25][Step 1/1] [10:11:49]: {:ENVIRONMENT=>"companyfriends_product", :PLATFORM_NAME=>nil, :LANE_NAME=>"testflight", :PRODUCE_APPLE_ID=>"1016409859", :CERT_FILE_PATH=>"/Applications/buildAgent/work/50e8e60632650931/products/certificates/identities/production/S43R88T2LX.cer", :CERT_CERTIFICATE_ID=>"S43R88T2LX", :SIGH_PROFILE_PATH=>"/Applications/buildAgent/work/50e8e60632650931/productoffice/products/provisioning_profiles/AppStore_com.companyfriends.productoffice.mobileprovision", :SIGH_PROFILE_PATHS=>["/Applications/buildAgent/work/50e8e60632650931/productoffice/products/provisioning_profiles/AppStore_com.companyfriends.productoffice.mobileprovision"], :SIGH_UDID=>"7f73d85e-8a59-4547-877f-555e16dec9ef", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Applications/buildAgent/work/50e8e60632650931/productoffice/products/IPA/productoffice.ipa", :DSYM_OUTPUT_PATH=>"/Applications/buildAgent/work/50e8e60632650931/productoffice/products/IPA/productoffice.app.dSYM.zip"}
[10:11:25][Step 1/1] [10:11:49]: Error uploading ipa file, more information see above
[10:11:25][Step 1/1] 
[10:11:25][Step 1/1] +------+-----------+-------------+
[10:11:25][Step 1/1] |        fastlane summary        |
[10:11:25][Step 1/1] +------+-----------+-------------+
[10:11:25][Step 1/1] | Step | Action    | Time (in s) |
[10:11:25][Step 1/1] +------+-----------+-------------+
[10:11:25][Step 1/1] | 1    | cocoapods | 14          |
[10:11:25][Step 1/1] | 2    | produce   | 16          |
[10:11:25][Step 1/1] | 3    | cert      | 9           |
[10:11:25][Step 1/1] | 4    | pem       | 3           |
[10:11:25][Step 1/1] | 5    | pem       | 2           |
[10:11:25][Step 1/1] | 6    | sigh      | 9           |
[10:11:25][Step 1/1] | 7    | gym       | 160         |
[10:11:25][Step 1/1] | 8    | pilot     | 241         |
[10:11:25][Step 1/1] +------+-----------+-------------+
[10:11:25][Step 1/1] 
[10:11:25][Step 1/1] [10:11:49]: fastlane finished with errors
[10:11:25][Step 1/1] -------------------------------------------------------------------------------------------
[10:11:25][Step 1/1]     An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
[10:11:25][Step 1/1]     This makes resolving issues much easier and helps improve fastlane.
[10:11:25][Step 1/1]     The reports will be stored securely on getsentry.com.
[10:11:25][Step 1/1] ✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
[10:11:25][Step 1/1]     More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
[10:11:25][Step 1/1] -------------------------------------------------------------------------------------------
[10:11:25][Step 1/1] /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/build_manager.rb:27:in `upload': Error uploading ipa file, more information see above (RuntimeError)
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/actions/pilot.rb:15:in `run'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:128:in `block in execute_action'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `chdir'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:127:in `execute_action'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/fast_file.rb:149:in `method_missing'
[10:11:25][Step 1/1] 	from Fastfile:133:in `block in parsing_binding'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/lane.rb:36:in `call'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:51:in `block in execute'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `chdir'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/runner.rb:46:in `execute'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/lib/fastlane/command_line_handler.rb:31:in `handle'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:35:in `block (2 levels) in run'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:152:in `run'
[10:11:25][Step 1/1] 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.39.0/bin/fastlane:158:in `<top (required)>'
[10:11:25][Step 1/1] 	from /usr/bin/fastlane:23:in `load'
[10:11:25][Step 1/1] 	from /usr/bin/fastlane:23:in `<main>'
[10:11:25][Step 1/1] Process exited with code 1
[10:11:25][Step 1/1] Step Build Release configuration and upload to iTunes connect (Command Line) failed
```

**Comment by siemensikkema** [comment]
I have the same problem. The build shows up on iTunes Connect but iTunes Transporter reports an error.

```
[18:44:40]: iTunes Transporter successfully finished its job
[18:44:40]: [Transporter]: DBG-X: Returning 0
[18:44:40]: The file, 6928cbfec807d536c2ce9be49870ab6d.ipa, did not complete its upload.
```
_private information removed_
```
[18:44:40]: Error uploading ipa file, more information see above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cert                                | 12          |
| 4    | sigh                                | 12          |
| 5    | increment_build_number              | 2           |
| 6    | commit_version_bump                 | 1           |
| 7    | gym                                 | 91          |
| 8    | pilot                               | 1727        |
+------+-------------------------------------+-------------+

[18:44:40]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'cba5b08ec6b19a3dcd7ae19f6a7c201b'
The crash report has been stored locally '/tmp/sentry_cba5b08ec6b19a3dcd7ae19f6a7c201b.json'
```

**Comment by KrauseFx** [comment]
The transporter pretty clearly states that the upload was not complete:

```
[10:11:25][Step 1/1] [10:11:49]: The file, df9449c4ffc10b21d76ccd444441e656.ipa, did not complete its upload.
```
so `pilot` handles this case correctly.

**Comment by siemensikkema** [comment]
You're (mostly) right. There appears to be a bug in iTMSTransporter. However, as @meirtz4 mentioned, the upload is retried _successfully_ but pilot does not pick up on this.

**Comment by KrauseFx** [comment]
`pilot` is just using the return status code it gets from the transporter, there is not much it can do.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1896. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
