### ISSUE TITLE
Error when trying to retrieve TestFlight tester data

### ISSUE THREAD

**Issue by tomdixon** [fastlane/pilot#85]
I'm getting the following error when running either `pilot list` or `pilot export`. It authenticates successfully but then gets an error response from iTunes Connect. `pilot builds` is working fine.

```
[18:22:40]: Login successful
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/client.rb:263:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:636:in `testers'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tester.rb:74:in `all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/tester_manager.rb:70:in `list_testers'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:76:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:120:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pilot-1.0.1/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

**Comment by foozmeat** [comment]
+1

**Comment by jorgeazevedo** [comment]
I get the same thing. `pilot list` requires an admin account because it hits this endpoint https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/users/pre/int . Tricky requirement! I suspect that using a different endpoint makes the implementation much more complicated.

**Comment by tomdixon** [comment]
Thanks @jorgeazevedo, worked when I switched to using an admin account

**Comment by KrauseFx** [comment]
@jorgeazevedo Do you know of an alternative endpoint that would allow us to support non-Admin accounts?

**Comment by bluefallsky** [comment]
here same using 'upload'.
pilot upload -u <user> -a <appid> -i <ipa-path>

below log
```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/client.rb:263:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unauthorized access"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/tunes/tunes_client.rb:181:in `applications'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/tunes/application.rb:62:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.2/lib/spaceship/tunes/application.rb:68:in `find'
		from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/manager.rb:41:in `fetch_app_id'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/manager.rb:21:in `app'
		from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/build_manager.rb:8:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:48:in `block (2 levels) in run'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
		from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
		from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:120:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/lib/pilot/commands_generator.rb:17:in `start'
		from /Library/Ruby/Gems/2.0.0/gems/pilot-1.0.1/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
		from /usr/local/bin/pilot:23:in `<main>'
```

**Comment by jorgeazevedo** [comment]
@KrauseFx I remember being able to see the devices for a testflight user with just a "technical" role account. I can't anymore, I suspect the major permissions overall iTC had a few weeks ago killed it : -(

I patched pilot to use https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/internalTesters/$id/ instead. Which works, but because of the above it doesn't list number of devices

**Comment by ashur** [comment]
+1

**Comment by caoer** [comment]
+1

**Comment by ahmedgharib** [comment]
Any news on getting this working with Technical roles?

**Comment by jaleksynas** [comment]
+1

**Comment by noamgat** [comment]
+1

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1895. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
